name: tools-update-changelog
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update_changelog:
    runs-on: [self-hosted, scripts]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: "LibreELEC/actions"
          path: "actions"

      - name: Update changelog at LibreELEC nightly repository
        run: |
          cd "actions/"
          ssh ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} -p ${{ secrets.NIGHTLY_HOST_PORT }} \
            "bash -s" < ./scripts/update_changelog.sh
